In [228]:
import numpy as np
import pandas as pd
import pickle

In [229]:
df = pd.read_csv('placement.csv')

In [230]:
df.shape

(200, 2)

In [231]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [232]:
df.describe()

cgpa     package
count  200.000000  200.000000
mean     6.990500    2.996050
std      1.069409    0.691644
min      4.260000    1.370000
25%      6.190000    2.487500
50%      6.965000    2.995000
75%      7.737500    3.492500
max      9.580000    4.620000

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.2 KB


In [234]:
X = df.iloc[:, 0].values

In [235]:
y = df.iloc[:, -1].values

In [236]:
X = X.reshape((len(X),-1))
y = y.reshape((len(y), -1))

In [237]:
from sklearn.model_selection import train_test_split

In [238]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [239]:
from sklearn.tree import DecisionTreeRegressor

In [240]:
dtree = DecisionTreeRegressor()

In [241]:
dtree.fit(X_train, y_train)

DecisionTreeRegressor()

In [242]:
y_pred = dtree.predict(X_test)

In [243]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.646920120760248

In [244]:
from sklearn.linear_model import LinearRegression

In [245]:
lr = LinearRegression()

In [246]:
lr.fit(X_train,y_train)

LinearRegression()

In [247]:
y_pred = lr.predict(X_test)

In [248]:
from sklearn.metrics import r2_score

In [249]:
y_test

array([[2.79],
       [3.23],
       [3.26],
       [3.04],
       [3.34],
       [4.21],
       [2.94],
       [2.87],
       [2.99],
       [3.58],
       [1.63],
       [2.08],
       [4.08],
       [2.21],
       [3.47],
       [3.64],
       [2.74],
       [3.08],
       [2.17],
       [2.99],
       [2.31],
       [2.35],
       [3.4 ],
       [3.08],
       [3.81],
       [2.19],
       [1.53],
       [2.89],
       [3.16],
       [2.48],
       [3.51],
       [2.98],
       [3.39],
       [3.28],
       [2.73],
       [3.74],
       [2.6 ],
       [3.13],
       [3.82],
       [3.15],
       [3.  ],
       [3.24],
       [4.36],
       [2.71],
       [2.01],
       [2.46],
       [3.49],
       [2.83],
       [1.54],
       [2.77]])

In [250]:
y_pred

array([[2.78658779],
       [3.14067821],
       [3.2035007 ],
       [2.39823057],
       [3.52903544],
       [3.76890314],
       [3.16923389],
       [2.55243123],
       [3.18065616],
       [3.49476862],
       [1.91849517],
       [2.35825262],
       [3.68894724],
       [2.76374325],
       [3.47763522],
       [3.04930004],
       [2.33540807],
       [3.20921184],
       [2.18691855],
       [3.31772342],
       [2.46105306],
       [2.90652164],
       [3.32343455],
       [2.87796597],
       [3.34056796],
       [2.20405195],
       [1.43304863],
       [2.71805417],
       [3.18636729],
       [2.33540807],
       [3.74605859],
       [2.963633  ],
       [3.6832361 ],
       [2.98076641],
       [2.59812032],
       [3.35199023],
       [2.4838976 ],
       [3.07785572],
       [4.17439377],
       [2.963633  ],
       [3.10070026],
       [3.11783367],
       [3.9231038 ],
       [2.72947644],
       [1.9242063 ],
       [2.95792187],
       [3.08356685],
       [3.272

In [251]:
lr.predict([[2.79]])

array([[0.59351168]])

In [252]:
model_accuracy=round(r2_score(y_test, y_pred)*100,3)

In [253]:
import json

In [254]:
#converting numpy array to list
model_accuracy=model_accuracy.tolist()

In [255]:
pickle.dump(lr, open('placement.pkl','wb'))
 #exporting to other
with open("data_file.json", "w") as wf:
    json.dump(model_accuracy, wf)


# pd.to_csv(y_test,"placement_test.csv")

In [256]:
#CGPA ---> LPA

In [257]:
# lr.predict([[8.1]])

In [258]:
# lr.predict(np.array([8.1]).reshape(-1,1))

In [259]:
# y_t = pd.read_csv('placement.csv').iloc[:,-1].values

In [260]:
# y_t.reshape([-1,1])

In [261]:
# y_t.shape